### ISSUE TITLE
Any channel beside sync doesn't work!

### ISSUE THREAD

**Issue by rsangin** [kasperdokter/Reo#12]
Hi, I'm using this compiler for my project but when I use any other channels like lossy sync, fifo, sync drain etc, output java file ends up in a **deadlock**. Even when I use the example you are providing in introduction file it doesn't work either. 
Am I doing something wrong or this is a bug in compiler?!

**Comment by k4r4c** [comment]
Hi, I need more details to help you. Which binaries are you using for compilation? Some changes have been made recently (on the binaries accessible at https://reo.readthedocs.io/en/latest/installation.html), it may have altered some of the behaviour. 
Could you also explain the details of the steps you are taking?

**Comment by rsangin** [comment]
Sorry I'm responding late. I am using reo-compiler code and I have pulled from origin\master too. I run the compiler with treo file that is used in your tutorial. My treo file is: 
```
import reo.syncdrain;
import reo.sync;
import reo.fifo1;

// The main component
main(a,b,c) { green(a) red(b) blue(c) alternator(a,b,c) }
	
// The atomic components
red(a!String) { #JAVA "Processes.Red" }
green(a!String) { #JAVA "Processes.Green" }
blue(a?String) { #JAVA "Processes.Blue" }
	
// The alternator protocol
alternator(a,b,c) { syncdrain(a, b) sync(b, x) fifo1(x, c) sync(a, c) }
```

and my java file is: 
```
import nl.cwi.reo.runtime.Input;
import nl.cwi.reo.runtime.Output;

public class Processes {

	public static void Red(Output<String> port) {
	   while (true) {
	      for (int i = 0; i < 30000000; ++i);
	      String datum = "Hello, ";
	      port.put(datum);
	   }
	}

	public static void Green(Output<String> port) {
	   while (true) {
	      for (int i = 0; i < 50000000; ++i);
	      String datum = "world! ";
	      port.put(datum);
	   }
	}

	public static void Blue(Input<String> port) {
	   for (int k = 0; k < 10; ++k) {
	      for (int i = 0; i < 40000000; ++i);
	         String datum = port.get();
	         System.out.print(datum);
      }
	}
	
}
```
There will be no output and when I look at jconsole, all threads are waiting.

**Comment by k4r4c** [comment]
Few comments on your code. The treo file is supposed to have the same name as the main component of your file. In your case, the treo file should be named "main.treo" (I guess you got it right if you didn't get any error messages). 
The main component can either hide all the internal ports (with an empty interface), or expose some ports for runtime i/o. In your case, ports a b c are open, and input/output request are expected at runtime. Your intention was perhaps to connect internally a and b to a producer (Red and Green) and c to a consumer (Blue). In this case, the declaration of the main component should have an empty interface: "main() { green(a) red(b) blue(c) alternator(a,b,c) }". Note that you can take inspiration from some examples in the folder examples/slides/main.

The rest looks fine, and compile&run on my side. Also, the for loop ( for (int i = 0; i < 50000000; ++i);) in your java code is used for each producer/consumer to wait? You might want to use Thread.sleep(time_ms) instead (such as: try{Thread.sleep(1000);}catch(InterruptedException e){System.out.println(e);}).
What I observe as output is "world! Hello, world! Hello, world! Hello, world! Hello, world! Hello,", which is 10 times the alternation of the two input strings.

My guess is that you want to let the interface of the main component empty. Doing that should solve your problem. Let me know if it works, if something is not clear, or if you have more questions.

**Comment by rsangin** [comment]
Yes, you're right. I wanted to use **internal ports**. I used the empty interface and every thing works fine. 
Thanks for your response.
