### ISSUE TITLE
Installer fails

### ISSUE THREAD

**Issue by salotz** [kasperdokter/Reo#13]
I'm on Ubuntu 18.04. I can click through the installer wizard but when it goes to actually install the pack it just hangs and shows no progress.

```
--> java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)

--> ./reo-installer-1.0.jar
Command line arguments: 
Gtk-Message: 22:17:18.168: Failed to load module "canberra-gtk-module"
Cannot find named resource: 'packsLang.xml' AND 'packsLang.xml_eng'
====================
Installation started
Exception in thread "IzPack - Unpacker thread" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at com.izforge.izpack.installer.unpacker.UnpackerBase.logIntro(UnpackerBase.java:253)
	at com.izforge.izpack.installer.unpacker.UnpackerBase.unpack(UnpackerBase.java:285)
	at com.izforge.izpack.installer.unpacker.UnpackerBase.run(UnpackerBase.java:242)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by k4r4c** [comment]
Thanks for sharing detailed logs. It turned out that the current IzPack module version used in the installer is not backward compatible with newer Java version. 
I removed it, and changed the installation method in https://github.com/ReoLanguage/Reo. 
Hope that helps!

**Comment by salotz** [comment]
Thank you for fixing that it is working for me now. 

Perhaps its my own personal bias but it is a very strange and a little confusing way to install it. The `install.sh` script just writes the readme and a shell environment script to the folder, it doesn't actually install anything. These files could just as easily be included in the zip file. The programs is actually zero install (or rather its up to you to put it in your PATH or make an alias etc). That is a perfectly reasonable way to install something. I think you could just get rid of the `install.sh` and the platform specific zips.

At this point just instruct people to clone the repo and link to the jar in the `bin` folder with different instructions for different platforms. Because the generated README references the examples in the git repo anyways and not the included examples.

**Comment by k4r4c** [comment]
The idea behind having an install script is that it automatically set the correct path in the README and initreo.sh files for specific platform (e.g Windows or Unix based). Then, as you say, it is up to you to set the variable locally to your current environment (by sourcing the file) or to set it permanently for any shell in your .bashrc (or equivalent). From my experience, not everyone is willing to clone the whole repository..

Perhaps we should rename the install.sh script to remove the confusion, and add explanation wrt aliases and path variables. 

Some examples are already in the archive. However, you pointed another mistake in the README: examples are found in the folder "./slides/main", not in the folder "./examples/slides/main".

**Comment by salotz** [comment]
Just some suggestions, I'll close this since it is solved.
